package app.page;

public enum Menu {
    HOME,
    MOVIE_BY_GENRE,
    USER_BY_JOB,
    MOST_VIEWED_FILMS_BY_PROFESSION,
    MOST_VIEWED_FILMS_BY_AGE_RANGE,
    TOP5_RATED_FILMS,
    INSERT_RATING_IN_FILMS_EMBEDDED
}
